//
// Created by cswu on 2018/12/15.
//

#ifndef FINALPORJECT_CONFIG_H
#define FINALPORJECT_CONFIG_H

#define FPS 60
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 1200

#endif //FINALPORJECT_CONFIG_H
